# changes in this file require restarting gastby development

extend type Mdx {
    meta: MdxMeta!
}

type MdxMeta {
    title: String!
    date: Date
    tags: [String!]!
    slug: String!
    description: String
}

extend type MdxFrontmatter {
    title: String
    date: Date
    tags: [String!]
    description: String
}
