import * as React from "react"
import { Article } from '~src/components/Article'

export default function Blog() {

    return <>
        <h1>Hi people</h1>
        <Article>
            {lorem}
        </Article>
    </>
}

Blog.title = 'foo'


const lorem = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Eget duis at tellus at urna condimentum mattis. Vulputate mi sit amet mauris. Elementum sagittis vitae et leo. Proin sagittis nisl rhoncus mattis. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Erat imperdiet sed euismod nisi porta. At auctor urna nunc id cursus metus aliquam eleifend. Molestie nunc non blandit massa enim.

Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Sed id semper risus in hendrerit gravida. Condimentum lacinia quis vel eros donec ac odio tempor. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Lorem ipsum dolor sit amet consectetur. Cursus turpis massa tincidunt dui ut ornare. Eget gravida cum sociis natoque penatibus. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Nunc id cursus metus aliquam eleifend mi in. Sit amet venenatis urna cursus eget. Non curabitur gravida arcu ac. Enim tortor at auctor urna nunc. Bibendum neque egestas congue quisque egestas diam in arcu. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Eu mi bibendum neque egestas congue quisque egestas. Et malesuada fames ac turpis.

Sem viverra aliquet eget sit amet tellus cras. Senectus et netus et malesuada. Odio eu feugiat pretium nibh ipsum. Netus et malesuada fames ac turpis egestas sed. Integer vitae justo eget magna fermentum iaculis eu non. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Pellentesque elit eget gravida cum sociis natoque penatibus. Nunc congue nisi vitae suscipit tellus mauris a diam. Sed libero enim sed faucibus turpis.

Imperdiet nulla malesuada pellentesque elit eget gravida cum. Aliquet sagittis id consectetur purus. Sit amet nisl suscipit adipiscing. Vitae auctor eu augue ut lectus. Leo in vitae turpis massa. Elit duis tristique sollicitudin nibh sit. Iaculis urna id volutpat lacus laoreet non curabitur. Scelerisque varius morbi enim nunc faucibus a pellentesque. Sed arcu non odio euismod lacinia at quis. Ipsum dolor sit amet consectetur adipiscing elit. Rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque purus semper eget duis. Integer malesuada nunc vel risus commodo. Porttitor rhoncus dolor purus non enim praesent.

Est ante in nibh mauris cursus mattis molestie a. Ut etiam sit amet nisl purus in. Lacus viverra vitae congue eu consequat ac. Velit scelerisque in dictum non consectetur a erat. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Mauris a diam maecenas sed enim ut sem viverra aliquet. Ac turpis egestas integer eget. Urna neque viverra justo nec ultrices dui sapien eget. Velit scelerisque in dictum non consectetur a erat. Nullam non nisi est sit amet facilisis magna. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Nunc non blandit massa enim nec dui nunc. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Arcu non sodales neque sodales ut etiam sit amet. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Lacus vel facilisis volutpat est velit egestas dui id ornare. Blandit massa enim nec dui nunc mattis. Nam at lectus urna duis convallis convallis tellus. Rhoncus dolor purus non enim praesent elementum facilisis leo. Sit amet facilisis magna etiam tempor orci eu lobortis elementum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Eget duis at tellus at urna condimentum mattis. Vulputate mi sit amet mauris. Elementum sagittis vitae et leo. Proin sagittis nisl rhoncus mattis. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Erat imperdiet sed euismod nisi porta. At auctor urna nunc id cursus metus aliquam eleifend. Molestie nunc non blandit massa enim.

Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Sed id semper risus in hendrerit gravida. Condimentum lacinia quis vel eros donec ac odio tempor. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Lorem ipsum dolor sit amet consectetur. Cursus turpis massa tincidunt dui ut ornare. Eget gravida cum sociis natoque penatibus. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Nunc id cursus metus aliquam eleifend mi in. Sit amet venenatis urna cursus eget. Non curabitur gravida arcu ac. Enim tortor at auctor urna nunc. Bibendum neque egestas congue quisque egestas diam in arcu. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Eu mi bibendum neque egestas congue quisque egestas. Et malesuada fames ac turpis.

Sem viverra aliquet eget sit amet tellus cras. Senectus et netus et malesuada. Odio eu feugiat pretium nibh ipsum. Netus et malesuada fames ac turpis egestas sed. Integer vitae justo eget magna fermentum iaculis eu non. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Pellentesque elit eget gravida cum sociis natoque penatibus. Nunc congue nisi vitae suscipit tellus mauris a diam. Sed libero enim sed faucibus turpis.

Imperdiet nulla malesuada pellentesque elit eget gravida cum. Aliquet sagittis id consectetur purus. Sit amet nisl suscipit adipiscing. Vitae auctor eu augue ut lectus. Leo in vitae turpis massa. Elit duis tristique sollicitudin nibh sit. Iaculis urna id volutpat lacus laoreet non curabitur. Scelerisque varius morbi enim nunc faucibus a pellentesque. Sed arcu non odio euismod lacinia at quis. Ipsum dolor sit amet consectetur adipiscing elit. Rhoncus est pellentesque elit ullamcorper dignissim cras. Scelerisque purus semper eget duis. Integer malesuada nunc vel risus commodo. Porttitor rhoncus dolor purus non enim praesent.

Est ante in nibh mauris cursus mattis molestie a. Ut etiam sit amet nisl purus in. Lacus viverra vitae congue eu consequat ac. Velit scelerisque in dictum non consectetur a erat. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Mauris a diam maecenas sed enim ut sem viverra aliquet. Ac turpis egestas integer eget. Urna neque viverra justo nec ultrices dui sapien eget. Velit scelerisque in dictum non consectetur a erat. Nullam non nisi est sit amet facilisis magna. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Nunc non blandit massa enim nec dui nunc. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Arcu non sodales neque sodales ut etiam sit amet. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Lacus vel facilisis volutpat est velit egestas dui id ornare. Blandit massa enim nec dui nunc mattis. Nam at lectus urna duis convallis convallis tellus. Rhoncus dolor purus non enim praesent elementum facilisis leo. Sit amet facilisis magna etiam tempor orci eu lobortis elementum.
`