name: Publish

on:
  push:
    branches:
    - master
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: bahmutov/npm-install@v1
    - run: yarn build
    - run: mv public docs
    - run: git add -f docs
    - name: Commit build
      run: >
        git diff --staged --quiet
        || (git config user.name "github-actions[bot]"
        && git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        && git commit -m "build: autoupdate"
        && echo "buildCommit=$(git rev-parse HEAD)" >>$GITHUB_ENV)
    - if: env.buildCommit # skip if the build adds nothing new
      name: Push gh-pages branch
      run: git push -f origin HEAD:gh-pages
